
AllCops:
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4

# Commented out because of rubocop bug, uncomment when generating todo file
Metrics/LineLength:
  Max: 100

Style/NumericLiterals:
  Enabled: false
